config/routes.rb
Rails.application.routes.draw do

match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

#Facebook login
# get 'auth/:provider/callback', to: 'sessions#create'
# get 'logout', to: 'sessions#destroy'

resources :posts
# get "/posts/new"        => "posts#new", as: :new_post
# post "/posts"           => "posts#create", as: :posts
# get "/posts/:id"        => "posts#show", as: :post
# get "/posts:id/edit"    => "posts#edit", as: :edit_post
# patch "/posts/:id"      => "posts#update"
# get "/posts"            => "posts#index"
# delete "/posts/:id"     => "posts#destroy"
# get "/posts"              => "posts#search", as: :search

root "posts#index"

resources :users, only:[:new, :create]

resources :sessions, only:[:new, :create] do
  delete :destroy, on: :collection
end

resources :posts do
    member do
      post :vote_up
      post :vote_down
    end

    post :search, on: :collection

    resources :comments

    resources :favourites, only:[:create, :destroy, :index]

  end

  # resources :snippets, only:[] do
  # resources :comments
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many(:comments, {dependent: :destroy})

  # taggings associations
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  # favourite associations
  has_many :favourites, dependent: :nullify
  has_many :favouriting_users, through: :favourites, source: :user

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

  mount_uploader :image, ImageUploader


  extend FriendlyId
  friendly_id :title, use: :slugged

  def self.search(search)
    if search
      where("title ILIKE? OR body ILIKE?", "%#{search}%", "%#{search}%")
    else
      all
    end
  end

  def favourited_by?(user)
    favourite_for(user).present?
  end

  def favourite_for(user)
    favourites.find_by_user_id(user.id)
  end

  # after_initialize :set_default_vote_counter

  #for better params SEO
  # def to_param
  #   "#{id}-#{title}".parameterize
  # end

  private

  def set_default_vote_counter
    self.vote_counter ||= 0
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, {only:[:show, :edit, :update, :destroy]}
  before_action  :authenticate_user, except: [:index, :show]
  before_action :authorize, only: [:edit, :update, :destroy]
  def index
    @post = Post.search(params[:search]).page(params[:page] || 1).per(3).order(vote_counter: :desc)
    # @post = Post.search(params[:search])
  end

  def new
    @post = Post.new
  end

  def create
    post_params = params.require(:post).permit([:title, :body, {tag_ids:[]}, :image])
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
     redirect_to(post_path(@post))
   else
     render :new
   end
  end

  def show
    @comment = Comment.new
  end

  def edit
    # @post = Post.find(params[:id])
    redirect_to posts_path, alert: "Access denied!" unless can? :edit, @post
  end

  def update
    # this will make friendly id regenerate a slug for you
    @post.slug = nil
    post_params = params.require(:post).permit([:title, :body, :image])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "Post updated!"
    else
      render :edit
    end
  end

  def destroy
    # @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: "Post Deleted"
  end

  def vote_up
    @post = Post.find params[:id]
    @post.increment!(:vote_counter)
    # session[:has_voted] = true
    redirect_to post_path
  end
  def vote_down
    @post = Post.find params[:id]
    @post.decrement!(:vote_counter)
    # session[:has_voted] = true
    redirect_to post_path
  end

  def authorize
    redirect_to root_path, alert: "Access Denied!" unless can? :manage, @post
  end

private


 def find_post
  #  @post = Post.find(params[:id])
   @post = Post.friendly.find(params[:id])
   # this will redirect the user to the new url if friendly id found the question using an old slug  
   redirect_to @post if @post.slug != params[:id]
 end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1>Edit</h1>

<div class="well new-post-resize">
  <% if @post.errors.any? %>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
      <!-- <p class="help-block">For post title</p> -->
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control", rows:"5" %>
    </div>
    <div class="form-group">
      <%= f.collection_check_boxes :tag_ids, Tag.order(:name), :id, :name  %>
    </div>
    <div>
      <br>
      <%= f.submit class: "btn btn-success" %>
      <%= link_to "Cancel", post_path(@post), class: "btn btn-default"%>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<!-- Intro Header -->
    <!-- <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="heading">Blogger</h1>
                        <p class="intro-text">A simple page for blogging.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header> -->

<h1>Posts</h1>
  <div class="panel panel-primary">
    <% @post.each do |post| %>
    <div class="panel-heading">
      <h3 class="panel-title"><%= link_to post.title, post_path(post) %></h3>
    </div>
    <div class="panel-body">
      <%= post.body.truncate(400, omission: '... (continued)') %>
      <% if post.user %>
      <p class="created-by"> Created by:
        <%= post.user.full_name %></p>
        <% end %>
      </p>
    </div>
  <% end %>
</div>
<%= paginate(@post) %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="well new-post-resize">
   <% if @post.errors.any? %>
    <ul class="error-message">
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %> 

  <!-- Using simple form gem to shorten form -->
  <%= form_for @post, html: {multipart: true} do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <%#= f.input :title, input_html: {placeholder: "Name of post"} %>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control", rows:"5" %>
    </div>
    <%#= f.input :body, hint: "Put details for the body"  %>
    <div class="form-group">
      <%= f.collection_check_boxes :tag_ids, Tag.order(:name), :id, :name%>
    </div>
    <div class="form-group">
      <%= f.file_field :image%>
    </div>
   <!--  </div>
    <%#= f.association :tags, as: :check_boxes %> 
    <div> -->
      <br>
      <%#= f.submit class: "btn btn-success" %>
      <%= f.submit :submit, class: "btn btn-success"%>
      <%= link_to "Cancel", posts_path, class: "btn btn-default"%>
    </div> 
  <% end %>
</div>

app/views/posts/show.html.erb
<h2 class= "post-resize">
  <% if user_signed_in? && @post.favourited_by?(current_user) %>
    <%= link_to fa_icon("star"), post_favourite_path(@post,
                        @post.favourite_for(current_user)), method: :delete %>
  <% else %>
    <%= link_to fa_icon("star-o"), post_favourites_path(@post),
                        method: :post %>
  <% end %>
  <%= @post.title %>
</h2>
<div class= "post-resize">
  <hr>
  <p><%= @post.body %></p>
  <hr>

  <!-- Tag -->
<div class="tags">
  <% if @post.tags.any? %>
    Tagged with:
    <% @post.tags.each do |tag| %>
      <div class="label label-primary" id="tags-show">
        <%= tag.name %>
      </div>
    <% end %>
  <% end %>
</div>

<!-- Image -->
   <p>
    <% if @post.image.present? %>
      <%= image_tag @post.image.url(:medium) %>
    <% else %>
      <p><i>No image available</i></p>
    <% end %>
  </p> 

<br>

  <div class="created-by">
    <% if @post.user %>
      <p> Created by:
      <%= @post.user.full_name %></p>
      <% end %>
    </p>
  </div>
</div>

<div class="post-resize">
  <% if can? :edit, @post %>
    <%= link_to "<i class='glyphicon glyphicon-pencil'></i> Edit".html_safe, edit_post_path(@post), class: "btn btn-info btn-sm" %>
  <% end %>
  <% if can? :delete, @post %>
    <%= link_to "<i class='glyphicon glyphicon-remove'></i> Delete".html_safe, post_path(@post), {method: :delete, data: {confirm: "Are you sure ?"}, class: "btn btn-danger btn-sm"} %>
  <% end %>
</div>

<br>
<div class="post-resize">
  <%= form_for [@post, @comment] do |f| %>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control", placeholder: "Enter a comment here"%>
    </div>
    <div>
      <%= f.submit class: "btn btn-primary btn-sm pull-right" %>
    </div>
  <% end %>
</div>
<br>
<div class="post-resize">
  <% if @post.comments.count < 5 %>
    Comments
    <% @post.comments.each do |comment| %>
      <div class="comments comments-bg">
        <% if can? :destroy, comment %>
         <%= link_to("<i class='glyphicon glyphicon-remove'></i>".html_safe,
                         post_comment_path(@post, comment), method: :delete,
                         class: "comment-delete",
                         data: {confirm: "Are you sure?"}) %>
       <% end %>
        <h4 class="user-name"><%= comment.user.first_name %></h4>
          <p>
            <%= comment.post.created_at.strftime("%B %d, %Y") %>
          </p>
          <p id="comments-body">
            <%= comment.body %>
          </p>
      </div>
      <% end %>
    <% else %>
  <button type="button" class="btn btn-info btn-xs" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Comments
    <span class="badge"><%= @post.comments.count %></span>
  </button>
  <div class="collapse" id="collapseExample">
    <% @post.comments.each do |comment| %>
      <div class="comments comments-bg">
        <% if can? :destroy, comment %>
         <%= link_to("<i class='glyphicon glyphicon-remove'></i>".html_safe,
                         post_comment_path(@post, comment), method: :delete,
                         class: "comment-delete",
                         data: {confirm: "Are you sure?"}) %>
       <% end %>
        <h4 class="user-name"><%= comment.user.first_name %></h4>
          <p>
            <%= comment.post.created_at.strftime("%B %d, %Y") %>
          </p>
          <p id="comments-body">
            <%= comment.body %>
          </p>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>