config/routes.rb
Rails.application.routes.draw do

match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

#Facebook login
# get 'auth/:provider/callback', to: 'sessions#create'
# get 'logout', to: 'sessions#destroy'

resources :posts
# get "/posts/new"        => "posts#new", as: :new_post
# post "/posts"           => "posts#create", as: :posts
# get "/posts/:id"        => "posts#show", as: :post
# get "/posts:id/edit"    => "posts#edit", as: :edit_post
# patch "/posts/:id"      => "posts#update"
# get "/posts"            => "posts#index"
# delete "/posts/:id"     => "posts#destroy"
# get "/posts"              => "posts#search", as: :search

root "posts#index"

resources :users, only:[:new, :create]

resources :sessions, only:[:new, :create] do
  delete :destroy, on: :collection
end

resources :posts do
    member do
      post :vote_up
      post :vote_down
    end

    post :search, on: :collection

    resources :comments

    resources :favourites, only:[:create, :destroy, :index]

  end

  # resources :snippets, only:[] do
  # resources :comments
end

app/views/layouts/_alert.html.erb
<% if flash[:notice]%>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_error_message.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
 <% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-nav">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <!-- <span class="sr-only">Toggle navigation</span> -->
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to fa_icon("home"), root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to("All Posts", posts_path) %></li>
        <li><%= link_to("New Post", new_post_path) %></li>
      </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <div>
              <%= form_tag posts_path, :method => "get", class:"navbar-form navbar-left", role:"search" do  %>
                <%= text_field_tag :search, params[:search], class:"form-control input-sm", placeholder:"Search"%>
              <%= submit_tag "Search", class: "btn btn-info btn-sm "%>
              <% end %>
              <div class="pull-right sign-in-out">
                <% if user_signed_in? %>
                  <%= current_user.first_name %>
                  |
                <% else %>
                  <%= link_to("Sign Up", new_user_path) %>
                  |
                  <%= link_to("Sign In", new_session_path) %>
                <% end %>
              </div>
            </div>
          </li>
          <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-cog"></i></a>
            <ul class="dropdown-menu" aria-labelledby="dLabel">
              <li><a href="#">Profile</a></li>
              <li><a href="#">My Posts</a></li>
              <li><% if user_signed_in? %>
                <%= link_to "Favourited", post_favourites_path(:post_id) %>
              <% end %></li>
              <li role="separator" class="divider"></li>
              <li>
                <% if user_signed_in? %>
                  <%= link_to("Logout", sessions_path, method: :delete) %>
                <% end %>
              </li>
            </ul>
          </li>
          <% end %>
        </ul>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Slab' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
  <script src="blog.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
      <%= render "/layouts/nav" %>
      <%= render "/layouts/alert" %>
    <%= yield %>
  </div>
</body>
</html>